// Compile-time secrets:
//   TMDB_TOKEN=eyJ... cargo build --release
//   ASHDI_TMDB_TOKEN=eyJ... cargo build --release
// Written into generated file so option_env always works via include!.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let token = env::var("TMDB_TOKEN")
        .or_else(|_| env::var("ASHDI_TMDB_TOKEN"))
        .unwrap_or_default();

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out.join("compiled_secrets.rs");
    let escaped = token.replace('\\', "\\\\").replace('"', "\\\"");
    fs::write(
        &dest,
        format!(
            "// @generated by build.rs — do not edit\n\
             pub const COMPILED_TMDB_TOKEN: &str = \"{escaped}\";\n"
        ),
    )
    .expect("write compiled_secrets.rs");

    println!("cargo:rerun-if-env-changed=TMDB_TOKEN");
    println!("cargo:rerun-if-env-changed=ASHDI_TMDB_TOKEN");
}
