use std::env;

// Generated by build.rs from TMDB_TOKEN / ASHDI_TMDB_TOKEN at compile time
include!(concat!(env!("OUT_DIR"), "/compiled_secrets.rs"));

pub struct Config {
    pub tmdb_token: String,
    pub timeout_secs: u64,
    pub user_agent: String,
    pub uaflix_cookie: Option<String>,
}

impl Config {
    pub fn from_env() -> Self {
        // Runtime env wins; else compile-time baked token
        let tmdb_token = env::var("TMDB_TOKEN")
            .or_else(|_| env::var("ASHDI_TMDB_TOKEN"))
            .ok()
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| {
                if COMPILED_TMDB_TOKEN.is_empty() {
                    String::new()
                } else {
                    COMPILED_TMDB_TOKEN.to_string()
                }
            });

        Self {
            tmdb_token,
            timeout_secs: 18,
            user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36".into(),
            uaflix_cookie: env::var("UAFLIX_COOKIE").ok().filter(|s| !s.is_empty()),
        }
    }
}
